brownfield-team/anacapa-github-linker

app/assets/javascripts/courses.js, app/models/course.rb, app/views/courses/_show_admin.html.erb, test/models/course_test.rb
Changed student_id to perm for csv upload/export to be consistent with database
=> Modified csv field names

Gemfile.lock, app/controllers/courses/roster_students_controller.rb, app/controllers/courses_controller.rb, app/models/ability.rb, app/views/courses/_show_admin.html.erb, test/controllers/courses_controller_test.rb, test/controllers/roster_students_controller_test.rb
Fixed permissions of instructors and TAs
=> Permissions

db/seeds.rb
The seeds.db file now has separate sections for development, production and test.
The fake users that we use for testing pagination are commented out.
=> fix up seeds.db file

Gemfile, Gemfile.lock
=> bumpBootstrapSaasGem

app/views/courses/roster_students/show.html.erb, test/controllers/roster_students_controller_test.rb
In this pull request, we add Github Id to the show page for Roster Student.
=> Pc add test for GitHub id on roster student show page

app/controllers/courses/roster_students_controller.rb, test/helpers/octokit_stub_helper.rb
=> Made auto pagination tests pass by adding mock stub

app/controllers/courses/roster_students_controller.rb
Fixed other contributor string creation for show roster_student repo table. Was causing page load to fail.
=> Made string slicing compatible with pre-ruby 2.5

app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/jobs/purge_unused_users_job.rb, app/views/users/index.html.erb
This PR implements the functionality discussed in #120 using url parameters. I still plan to implement better tables overall, but this allows filtering for the time being. This PR closes #120. Screenshot:
=> Added filtering to /users list page

app/views/courses/_show_admin.html.erb
Implements functionality described in and closes #135.
=> Added TA column to course students table

app/assets/stylesheets/application.scss, app/controllers/courses/roster_students_controller.rb, app/controllers/courses_controller.rb, app/jobs/refresh_github_repos_job.rb, app/jobs/repo_collaborators_job.rb, app/models/course.rb, app/models/github_repo.rb, app/models/repo_contributor.rb, app/models/user.rb, app/views/courses/roster_students/show.html.erb, db/migrate/20200104072015_add_full_name_to_github_repos.rb, db/migrate/20200104085704_create_repo_contributors_table.rb, db/migrate/20200104214922_drop_github_repos_users.rb, db/migrate/20200106180359_change_columns_of_repo_contributors.rb, db/schema.rb
This does the same stuff described in #116 and this PR has been opened to undo the revert. Do **not** merge this PR until it can be rebased to include all the exception handling stuff implemented in #144.
Precisely, this reverts the reversion of #116 and fixes one line where a breakpoint was left in.
=> Add contributor matching to repos

app/assets/javascripts/courses.js, app/assets/stylesheets/courses.scss, app/views/courses/_show_admin.html.erb
This PR overhauls the UI of the student CSV upload menu. It looks like this: 
The first row is only greyed and bolded when "First row is a header" is checked. "First row is a header" is now checked by default.
Additionally, basic auto matching of fields is implemented. If the first row of a column in a CSV roughly matches the name of a field, that field will automatically be selected in the dropdown (fields selected in the screenshot were matched this way).
We should merge this PR before Monday, as that's when the linker will be demoed to others. This closes #128.
=> Improved CSV upload UI by rotating menu and other features

app/assets/javascripts/courses.js, app/models/roster_student.rb, app/views/courses/_show_admin.html.erb
Note that the db column and any internal references are not changed. If these should also be changed, then let me know. This closes #175.
=> Superficially removed outward facing references to perm with student ID

app/views/users/index.html.erb
=> add labels to users index (closed #181)

app/jobs/course/associate_slack_users_job.rb, app/models/slack_user.rb, app/views/courses/_show_admin.html.erb, app/views/courses/roster_students/show.html.erb, app/views/courses/slack/show.html.erb, test/controllers/roster_students_controller_test.rb
This does everything described in and closes #193
=> Minor patches to Slack integration

app/assets/stylesheets/application.scss, app/controllers/slack/auth_controller.rb, app/views/courses/roster_students/show.html.erb
Fields on show student page are now displayed horizontally
=> Minor UI changes to show student page, associate slack users job now runs when slack added to course

app/controllers/courses/roster_students_controller.rb, app/models/course.rb, app/views/courses/_show_admin.html.erb, test/models/course_test.rb
In this PR, we add a button to download the Roster Students in Json format.
We also tidy up the UI a bit.
=> pc - add json download button

app/controllers/api/visitors_controller.rb, app/javascript/components/home/HomePage.jsx, app/javascript/packs/react-bundle.js, app/javascript/services/service-routes.js, app/javascript/services/visitors-service.js, app/views/api/visitors/_course.json.jbuilder, app/views/api/visitors/index.json.jbuilder, app/views/visitors/index.html.erb, config/routes.rb, test/controllers/courses_controller_test.rb, test/controllers/visitors_controller_test.rb
This PR provides a faithful reimplementation in React of the home page's course list display. No functionality or UI elements are changed, but an API controller to feed the React component as well as the React component itself is implemented.
=> Refactor home page to use React

app/controllers/api/courses/job_log_controller.rb, app/controllers/api/job_log_controller.rb, app/javascript/components/Jobs/JobLog.jsx, app/views/admin/dashboard.html.erb, app/views/courses/github_repos/show.html.erb, app/views/courses/jobs.html.erb, config/routes.rb
In this PR, I refactored the job log to be json data and the job log will now automatically refresh the display every 10 seconds. The 10 seconds are also configurable to be any amount of time.
=> Refactored Job Log to refresh display every 10 seconds

app/controllers/courses_controller.rb, app/javascript/components/CourseNavBar/CourseNavBar.jsx, app/models/course.rb, app/views/layouts/courses.html.erb, config/routes.rb, db/schema.rb
This PR adds the functionality to download pull requests' data for all teams in a course, in a single CSV file.
=> Download pull requests' data in CSV file

app/javascript/components/home/HomePage.jsx, app/views/api/visitors/_course.json.jbuilder, db/schema.rb, test/cypress/integration/home_spec.js
In this PR, I redesigned the home page to be a table that includes the school name, term, course organization, and a join button that disappears if the user is already in the course.
=> Redesigned home page to be a table instead of a list

app/jobs/repo/course_github_repo_get_issues.rb, app/jobs/repo/course_github_repo_get_pull_requests.rb, app/jobs/repo/course_github_repo_get_sdlc_events.rb, app/poros/job_result.rb, test/poros/job_result_test.rb
In this pr, we add the functionality for issues to include course start and end dates.
=> At get issue dates

app/jobs/repo/course_github_repo_get_pull_requests.rb
In this PR, we add the functionality to store pull requests w.r.t course start and end dates.
=> Store pull requests w.r.t course start and end dates.

app/controllers/api/courses/org_teams_controller.rb, app/javascript/components/Course/Analytics/ChangeAnalytics.jsx, app/javascript/components/Course/Analytics/CommitsAnalytics.jsx, app/javascript/components/Course/OrgTeams/CourseOrgTeam.jsx, app/javascript/components/Course/OrgTeams/CourseOrgTeamsIndex.jsx, db/migrate/20210803074907_add_repo_id_to_org_team.rb, db/schema.rb
In this PR, I fixed the infinite loading problem that occurs on the teams page when no teams or project repos are found.
=> Fix infinite loading

app/controllers/api/courses/org_teams_controller.rb, app/javascript/components/Course/Analytics/ChangeAnalytics.jsx, app/javascript/components/Course/Analytics/CommitsAnalytics.jsx, app/javascript/components/Course/OrgTeams/CourseOrgTeam.jsx, app/javascript/components/Course/OrgTeams/CourseOrgTeamsIndex.jsx, db/migrate/20210803074907_add_repo_id_to_org_team.rb, db/schema.rb
In this PR, we added labels for each dropdown on the github teams page. One label for changing the team and one label for assigning a github repo to the team.
=> Label dropdowns on teams page

app/javascript/components/Course/Analytics/ChangeAnalytics.jsx, app/javascript/components/Course/GithubRepos/CourseGithubReposTable.jsx, app/javascript/components/Course/OrgTeams/CourseOrgTeam.jsx, db/schema.rb
In this PR, I added information for the project repo onto our teams page. If no project repo is assigned, the table does not show up.
=> Added repo information to teams page

app/javascript/components/Courses/CoursesIndex.jsx
bh - replaced the hidden text on the courses page with a button to show or hide a course
Closes #391 
Replaces PR #450
=> bh - replaced the hidden text on the courses page with a button to show or hide a course

app/javascript/components/Courses/CoursesIndex.jsx
Moved Hide Course button next to the edit and delete button and only have it appear if your an instructor of the course of an admin.
=> Moving Hide button and making it hidden to non-authorized users

.github/workflows/ci-backend.yml, .github/workflows/ci-playwright.yml, Gemfile, Gemfile.lock, README.md, app/javascript/components/Courses/CoursesIndex.jsx, package.json, test/javascript/components/Courses/CoursesIndex.test.js, yarn.lock
This PR adds jest testing to the code base and it adds one Test that has full test coverage. The one test covers all of CoursesIndex.jsx. CoursesIndex.jsx was also changed from the old react state style of coding to the new hooks style. This was to start updating the code base to match the code bases from other courses (CS 156) and make it easier to write tests. 
Note: The tests all pass but some of them still raise the warning below and this should be fixed in a later PR. The error comes from the UseEffects call. A possible solution to this warning would be to use useQuery to make api requests.
```
console.error
Warning: An update to CoursesIndex inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* …
```
=> Adding jest testing

.github/workflows/ci-frontend-coverage.yml, .github/workflows/ci-frontend-tests.yml, package.json
Added github workflow scripts for the frontend tests and frontend coverage.
=> added frontend github workflow

.gitattributes, Gemfile.lock
in this pr we add a `.gitattributes` file to define the line endings and we update the ruby version
=> bh - update line endings and ruby version
