brownfield-team/anacapa-github-linker

.travis.yml
This PR addresses a problem where Travis CI jobs were failing because for some reasons Postgres was not being loaded.
(This wasn't a problem in the past, but maybe now you have to request Postgres explictly
in the .travis.yml).
=> pc - fix postgres on TravisCI

.env.example, .gitignore, .travis.yml, README.md, dotenv.example
The instructions in README.md for setup on localhost were not very clear.   It may have created the impression that the contents of .env were actually a shell script for defining environment variables, but that is not the case.
Instead, they are intended for use with the `dotenv-rails` Gem.  This change makes that clear.
=> pc - update README.md with clearer instructions for localhost setup

.travis.yml, app/controllers/visitors_controller.rb, app/views/visitors/index.html.erb, test/controllers/visitors_controller_test.rb, test/fixtures/courses.yml
Hidden courses should not be shown on the index page.
We added that code into the app previously and it worked in test, but not in production, so we backed the change out.   I discovered that the problem was that we were checking 
```
@courses = Course.where(hidden: false)
```
when we should have been checking:
```
@courses = Course.where.not(hidden: true)
```
The problem was that when we added the new `hidden` field, we didn't populate the null values with false.  Thus the first query gave us no courses at all, since hidden was not false for any of them in the production database.  
This could have been avoided if we had followed this advice:
<https://thoughtbot.com/blog/avoid-the-threestate-boolean-problem>
The "right" way to fix this was with a migration.  Instead, I just …
=> pc - don't show hidden courses on index page

app/controllers/courses_controller.rb, db/seeds.rb, test/controllers/courses_controller_test.rb, test/fixtures/courses.yml
In this pull request, I add some better error handling for the case where inviting a user to an organization fails.    
The new code checks to see if the Octokit call works before adding rows in the database.  It also passes along the error message from the exception to help with debugging problems when they occur.
I also clarify that the code *invites* the user; it does not add the user.   
There are also a few commits to clean up the seeds and fixtures.   There is more work to be done there, but that should be done in a separate pull request.
=> Pc better error handling for invites

app/controllers/courses_controller.rb
This PR addresses the situation where UCSB student emails are being converted from `user@umail.ucsb.edu` (the format that still appears on course rosters downloaded from eGrades) to `user@ucsb.edu`.
It is a risky change because it is not covered by tests.  Writing proper test cases for this would require considerable refactoring; the code is not currently well structured to test this.    That should eventually be done, but at the moment, it's more important to deliver value for our users.    
It has been tested only by putting in a `pry` statement on the data structure and checking that both `@umail.ucsb.edu` and `@ucsb.edu` addresses get added into the hash under both formats.    That's not perfect, but it may have to do.
=> pc - add hack for umail.ucsb.edu to ucsb.edu email conversion

app/controllers/users/omniauth_callbacks_controller.rb, app/models/user.rb, app/views/users/index.html.erb
In this PR we fix a bug where students that have changed their github username are not able to use the github linker.    
In the past, the username and "name" fields (given name) were updated in the database only at the first login from OAuth.  If a user than changed their username, subsequent attempts to add courses failed.    This PR should fix that.
In addition, if a student changed their given name in the past (e.g. from Christopher to Chris) or added a given name where it was previously blank, that would not be picked up.   Now, each time the user logs out of github completely, and then logs back into the github linker via OAuth, the information is updated.
=> Pc update email name username from GitHub at login

app/views/users/index.html.erb
This PR adds username and uid to the users page.  
This is intended to help when debugging problems that arise when github users change their username (but keep the same uid).
=> pc - add username/uid to users page to help debug OAuth issues

app/controllers/courses_controller.rb, app/models/course.rb, app/views/courses/_show_admin.html.erb, app/views/courses/roster_students/index.html.erb
This PR fixes a long standing bug, where there was an Org Membership column, but it was empty because the code to make it work had never been implemented.
There currently isn't test coverage for this.    We should add that in a separate PR.  But I'd like to get this into the app asap.
=> pc/fs - fix org membership column

app/controllers/courses/roster_students_controller.rb, app/views/courses/roster_students/show.html.erb, test/controllers/roster_students_controller_test.rb, test/helpers/octokit_stub_helper.rb
This pull request partially addresses issue #89. It implements a rudimentary substring matching way of listing a student's GitHub repositories within a course organization. For reasons elaborated on in exhaustive detail [here](https://github.com/project-anacapa/anacapa-github-linker/issues/89#issuecomment-548261898), it is resource prohibitive to use GitHub's API to generate a list of repositories in an organization that a user has either created or contributed to. For this reason, @pconrad and I decided to implement this functionality for the time being by simply showing repositories in the organization whose name contain the user's GitHub organization.
It implements a table on the show roster_student page that contains three things:
* The repository's name, which is a hyperlink to the …
=> Add table of student's repositories to show roster_student page

lib/Octokit_Wrapper.rb, test/helpers/octokit_stub_helper.rb
This PR fixes the issue that was causing the user repo list to not work correctly. This was happening because GitHub only returns the first page of results when you request a list of organization repos (30 repos total) unless auto=pagination is enabled. This PR enables auto-pagination. It does make the load of a roster_student page fairly slow for large organizations so in a later change, the repo list will be factored out into a separate page.
=> Enabled auto pagination as a stopgap fix

Gemfile, Gemfile.lock, app/views/layouts/_nav_links_for_auth.html.erb, app/views/visitors/_splash.html.erb, test/controllers/visitors_controller_test.rb
This PR resolves some not-flagrant-but-also-kinda-sketchy authentication practices present in the app's code. This resolves the [CVE 2015 9284](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9284) flagged by GitHub in the repo's security section. Though our configuration would not have allowed the kind of attack discussed in the vulnerability report, it still contains certain discouraged practices, namely the use of GET calls for Omniauth authorization. Specifically, this PR makes the following simple changes:
- The omniauth-rails_csrf_protection gem is added to the Gemfile. This gem just prevents any Omniauth calls from being anything other than a POST call unless explicitly overriden.
- The navigation bar and splash page sign-in links have been updated to POST calls to the …
=> Added omniauth-rails_csrf_protection gem and updated auth calls to POST

app/controllers/admin_controller.rb, app/controllers/courses_controller.rb, app/jobs/admin_job.rb, app/jobs/background_job.rb, app/jobs/course_job.rb, app/jobs/purge_completed_jobs_job.rb, app/jobs/purge_unused_users_job.rb, app/jobs/refresh_github_repos_job.rb, app/jobs/students_org_membership_check_job.rb, app/jobs/test_job.rb, app/models/completed_job.rb, app/models/course.rb, app/views/admin/dashboard.html.erb, app/views/admin/resource_dashboard.html.erb, app/views/courses/jobs.html.erb, app/views/layouts/_navigation_links.html.erb, app/views/visitors/index.html.erb, config/routes.rb
Apologies for another huge PR, it was necessary to change everything at once in order to implement all the functionality.
This PR implements/does the following things:
* It creates an admin dashboard for db resource management at the path admin/dashboard. It includes a table that lists each table of the db and how many rows that table uses (plus a total row count). This closes #109
* In this dashboard is also a job menu, for "admin jobs". Currently, there are two admin jobs: purge unused users (as described in #111) and purge all completed job records (for all courses + admin jobs).
* To implement these admin jobs, this PR creates a new superclass for asynchronous jobs in this project: BackgroundJob. Two classes inherit directly from BackgroundJob: CourseJob and AdminJob. CourseJob acts …
=> Admin dashboard and significant job refactoring

app/controllers/courses_controller.rb, app/jobs/purge_course_repos_job.rb, app/jobs/refresh_github_repos_job.rb, app/jobs/students_org_membership_check_job.rb
This PR closes #110. 
It simply implements a `Purge Course GitHub Repo Records from DB` job that when run, destroys the cached database rows that correspond to each GitHub repos in the course organization.
The GitHub repos themselves are NOT AFFECTED, and if all works as expected, the effect of running this job can be reversed by re-running the `Refresh Course GitHub Repo Records in DB` job.  That one recreates those records.
=> Added repo purge job for course

Gemfile, Gemfile.lock, app/controllers/admin_controller.rb, app/views/admin/dashboard.html.erb
This PR adds a rate limit table to the admin dashboard so administrators can see when the app has reached its GitHub API (and perhaps others in the future) limit or is getting close to it. The table looks like this: 
This closes #122.
=> Added rate limit table to admin dashboard

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/jobs/admin_job.rb, app/jobs/background_job.rb, app/jobs/course_job.rb, app/jobs/purge_completed_jobs_job.rb, app/jobs/purge_course_repos_job.rb, app/jobs/purge_unused_users_job.rb, app/jobs/refresh_github_repos_job.rb, app/jobs/students_org_membership_check_job.rb, app/jobs/test_job.rb, app/views/admin/dashboard.html.erb, app/views/courses/jobs.html.erb
This PR implements hover text describing the specific actions of a job on the job run menu as described in #121. Screenshot of what it looks like below:
This closes #121.
=> Added hover text description to jobs on job run menus

app/jobs/admin_job.rb, app/jobs/background_job.rb, app/jobs/course_job.rb, app/jobs/purge_completed_jobs_job.rb, app/jobs/purge_course_repos_job.rb, app/jobs/refresh_github_repos_job.rb, app/jobs/students_org_membership_check_job.rb, app/jobs/test_job.rb
This PR implements the refactor we talked about whereby exception handling and the connection pool are handled in the superclass ``Background Job``. The reference implementation is as follows (and found in the class):
```ruby
def perform
ActiveRecord::Base.connection_pool.with_connection do
begin
create_in_progress_job_record
attempt_job
rescue Exception => e
rescue_job(e)
end
end
end
def attempt_job
end
def rescue_job(exception)
update_job_record_with_completion_summary("An exception occurred. Please see the logs for more info.")
raise exception
end
```
Where the ``attempt_job`` method is overridden by each job class to implement its functionality, and perform is no longer overridden except where necessary as in ``CourseJob`` to overload with the ``course_id`` parameter. If a job throws …
=> Refactored jobs to allow for proper exception handling and avoid code reuse

app/views/courses/_show_admin.html.erb
This PR simply implements the functionality described in #134:
>On the page
>https://ucsb-cs-github-linker.herokuapp.com/courses/:course_id
>right after the place where it says:
> This course belongs to the github organization: ucsb-cs56-w20
> Add a link that says:
> See Membership and Pending Invitations
> and have the text "Membership and Pending Invitations" link to, for example:
> https://github.com/orgs/ucsb-cs56-w20/people
Screenshot:
This closes #134.
=> Add GitHub membership and invitations link to admin show course page

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/views/admin/dashboard.html.erb, app/views/courses/_show_admin.html.erb, app/views/courses/jobs.html.erb, app/views/users/index.html.erb
This PR implements fancy tables using the bootstrap-table-rails gem. It updates job logs, the users list page, and the course index page that shows the list of students in the course. A fully-featured table in the app looks like this:
We implement search, configurable and toggle-able pagination (client-side at the moment), sorting by a column's contents and only showing certain columns.
This closes #120 in a much more epic fashion.
=> Implemented bootstrap tables with many data table features

app/jobs/refresh_github_repos_job.rb
This was caused by a typo in an if statement that was not inverted properly. The issue was inadvertently introduced two days ago while implementing the ``attempt_job`` method.  Merge ASAP as the change is small but important.
=> Fixed critical issue causing refresh repo job to fail every time

app/assets/stylesheets/application.scss, app/controllers/courses/roster_students_controller.rb, app/controllers/courses_controller.rb, app/jobs/refresh_github_repos_job.rb, app/models/github_repo.rb, app/views/courses/_show_admin.html.erb, app/views/courses/repos.html.erb, app/views/courses/roster_students/show.html.erb, config/routes.rb, db/migrate/20200201195311_add_visibility_to_github_repos.rb, db/schema.rb
Note: The branch this PR is based off of is literally branched from fs-RevertReversionOfContributorMatching (#145) and so should not be merged before that one. This PR is marked as a draft accordingly.
This PR implements the functionality described in #146, with the exception of team functionality:
> As an admin of a course organization, I can
> (a) Enter a regular expression
> (b) I will then get a list of repos that match that regular expression
> (c) That list will have links to each repo, but also columns for:
> (i) public vs. private
> (ii) list of collaborators on the repo (annotated with their level of access)
> (iii) list of teams that have access to the repo (annotated with their level of access)
The page looks like this:
It is very similar to the repository table on a student's …
=> Implemented course repository regex search page

app/controllers/courses_controller.rb, app/jobs/admin_job.rb, app/jobs/background_job.rb, app/jobs/course_job.rb
This PR implements a ``permission_level`` variable for background jobs in the app. This doesn't currently change any functionality as default permissions will have the same behavior as before but it will allow job-specific permissions to be set e.g. RepoContributorJob can be set to admin only despite being a CourseJob. This PR closes #123.
=> Added permission levels to jobs and added check in course job menu

app/assets/javascripts/application.js, app/assets/javascripts/courses.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/courses.scss, app/jobs/repo_collaborators_job.rb, app/jobs/students_org_membership_check_job.rb, app/views/admin/dashboard.html.erb, app/views/courses/_show_admin.html.erb, app/views/courses/repos.html.erb, app/views/layouts/_nav_links_for_auth.html.erb
This PR implements a variety of minor UI fixes and a couple cool UI features. It does not make any functionality changes. Specifically, it does the following things:
- The nav bar sign in button is no longer half cutoff the page (finally!). This closes #161.
- The admin dashboard tables are reordered to be more helpful per the order described in #162:
> Put rate limit at top, jobs, job log, then db tables
Accordingly, this closes #162.
- The table of students on a course page is now even fancier. As a starter, the perm column is now sortable (this closes #163). But more importantly, the table can now be filtered by any one column of the user's choice. For the boolean fields, you can select true or false and it'll filter (this closes #164). For anything else, you can type anything into the …
=> Made various UI tweaks and fixed typos

app/controllers/courses_controller.rb, app/jobs/background_job.rb, app/jobs/course_job.rb, app/jobs/students_org_membership_check_job.rb, app/jobs/update_github_repos_job.rb, app/views/courses/_show_admin.html.erb, db/migrate/20200217182646_add_node_id_to_github_repos.rb, db/migrate/20200218024140_add_org_membership_type_to_roster_students.rb, db/schema.rb
Here's a helpful one. This PR implements GitHub API job functionality using the GraphQL interface to dramatically speed up processing and avoid counting too hard against the rate limit. It does the following:
- A new job is implemented: UpdateGithubReposJob. This job uses GraphQL to make one query to get all of an organization's repositories **and** their direct collaborators. This means we can effectively combine the RepoCollaboratorJob and RefreshGithubReposJob into one and, much more importantly, we don't need to make one query for every repository to get the collaborators. Whereas the old RepoCollaborator job was O(n) for n repositories, this is O(1).
- Refresh student org membership is also upgraded to GraphQL to implement the functionality requested in #136. The org membership …
=> Significantly improved GitHub API interactions using GraphQL

app/controllers/admin_controller.rb, app/controllers/application_controller.rb, app/controllers/courses/teams_controller.rb, app/controllers/courses_controller.rb, app/jobs/background_job.rb, app/jobs/course/associate_slack_users_job.rb, app/jobs/course/create_github_teams_job.rb, app/jobs/course/create_team_repos_job.rb, app/jobs/course/purge_course_repos_job.rb, app/jobs/course/refresh_github_teams_job.rb, app/jobs/course/students_org_membership_check_job.rb, app/jobs/course/test_job.rb, app/jobs/course/update_github_repos_job.rb, app/jobs/course_job.rb, app/views/courses/teams/create_teams.html.erb, app/views/courses/teams/show.html.erb, config/routes.rb
Full disclosure: this is messy and probably not that useful.
This PR implements the functionality described in #194 (and, as such, closes #194). It does the following things:
- Refactored job code to use an options hash in perform method to allow for any number of parameters to be passed to a job. No functionality changes here, but that's what all those ``options`` variables are.
- Minor refactor of github_machine_user into ``ApplicationController`` so the machine user code isn't repeated in a bunch of controllers.
- Adds the GitHub v3 API rate limit to admin dashboard. The v4 API does not support creating teams and editing their membership, so the new stuff relies on v3.
- A new view is added at endpoint ``/courses/:course_id/teams/create_teams`` and can be accessed via the "Manage …
=> Create GitHub teams from CSV

app/assets/javascripts/courses.js, app/controllers/courses/roster_students_controller.rb, app/controllers/slack/commands_controller.rb, app/models/course.rb, app/models/org_team.rb, app/models/roster_student.rb, app/views/courses/_show_admin.html.erb, app/views/courses/roster_students/_form.html.erb, app/views/courses/roster_students/edit.html.erb, app/views/courses/roster_students/show.html.erb, db/migrate/20200403222035_add_section_to_roster_students.rb, db/schema.rb, test/controllers/roster_students_controller_test.rb, test/fixtures/files/duplicate_email.csv, test/fixtures/files/duplicate_perm.csv, test/fixtures/files/students.csv, test/fixtures/files/students2.csv, test/models/course_test.rb
This PR implements everything in the following issues:
- Closes #113
- Closes #186
- Closes #201
- Closes #202
As described in those issues, it adds section and team info to the /whois slack command. Additionally, it adds a section field to roster_student (including CSV IO and show/edit/index table display). Finally, org membership status and teams a student is a member of are added to the downloaded CSV.
=> Added section to roster student, improved /whois slack command

Gemfile, Gemfile.lock, app/controllers/admin_controller.rb, app/controllers/courses/github_webhooks_controller.rb, app/controllers/courses_controller.rb, app/controllers/github_webhooks_controller.rb, app/controllers/slack/commands_controller.rb, app/models/application_record.rb, app/models/course.rb, app/models/github_repo.rb, app/models/github_webhook.rb, app/models/org_webhook.rb, app/models/student_team_membership.rb, app/views/admin/dashboard.html.erb, app/views/courses/_form.html.erb, app/views/layouts/_navigation_links.html.erb, app/views/visitors/index.html.erb, config/routes.rb, db/migrate/20200405063917_add_github_webhooks_enabled_to_courses.rb, db/migrate/20200405072640_create_github_webhooks.rb, db/schema.rb, dotenv.example, lib/Octokit_Wrapper.rb
This closes #206, closes #207, closes #208, closes #222, and closes #209.
It implements webhook integration for courses for all the purposes that GitHub-related jobs currently serve (and with the added benefit of deleting data when it is deleted on GitHub). Webhooks are added to a course by checking the "Enable GitHub webhooks" box on the course edit/create page. 
I don't have time to fully write everything up right now but I figured I'd leave this here because it's a lot of code to review so we can merge it during our thursday meeting.
=> GitHub webhooks integration

app/controllers/courses/org_teams_controller.rb, app/controllers/courses/project_teams_controller.rb, app/controllers/courses/roster_students_controller.rb, app/controllers/courses/slack_controller.rb, app/controllers/courses_controller.rb, app/javascript/bundles/CourseNavBar/components/CourseNavBar.jsx, app/javascript/bundles/ProjectTeams/components/Dashboard/TeamsDashboard.jsx, app/javascript/bundles/Users/components/Users.jsx, app/javascript/bundles/Users/components/UsersSearch.jsx, app/javascript/packs/react-bundle.js, app/views/courses/_show_admin.html.erb, app/views/courses/edit.html.erb, app/views/courses/jobs.html.erb, app/views/courses/org_teams/index.html.erb, app/views/courses/project_teams/index.html.erb, app/views/courses/repos.html.erb, app/views/courses/roster_students/show.html.erb, app/views/courses/show.html.erb, app/views/courses/slack/show.html.erb, app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb, app/views/layouts/courses.html.erb, app/views/layouts/users.html.erb, app/views/layouts/visitors.html.erb
This PR implements a reorganization of the course UX as well as several other minor UI changes. Specifically:
- A new React navigation bar is implemented for a course which can be used to navigate between different menus like the Repos page, Project Teams page etc. quickly. It looks like this: 
- A minor fix is made to the search field on the Users page to make the labels aligned.
- Many layout files are added to avoid UI code replication.
=> Added course navigation bar and various other course UI tweaks

app/models/course.rb
In this PR, we add three new fields to the CSV export of roster students:
* slack_uid
* slack_username
* slack_display_name
This is to aid in tagging Slack export data with the team that the student is associated with.  The exported CSV file will be consumed by tools that analyze the exported .zip file of a Slack workspace.
=> pc/at - add slack info to CSV export of student roster

app/views/courses/org_teams/create_teams.html.erb
This PR fixes a typo in the instructions on the create teams from CSV page
=> pc - fix typo in instructions for creating teams from CSV

app/jobs/admin/purge_completed_jobs_job.rb, app/jobs/admin/purge_unused_users_job.rb
In this PR we fix bug #268 where admin jobs can no longer run.
* STR: Try to run any admin level job
* Observed: Job crashes with "incorrect number of parameters"
* Desired: Jon runs successfully
Root cause: code for course level jobs was refactored, but code for admin level jobs was not refactored to match.
Solution: Add `(_options)` parameter (ignored) to `attempt_job` method of admin level jobs. (`_options` syntax signals to style checkers that the coder knows it is an unused variable, and that that fact should be ignored.)
=> pc - fix bug #268 (admin level jobs crash wrong num params)

app/javascript/components/CourseNavBar/CourseNavBar.jsx
This PR makes a small UI change on the course page.
Instead of a tab "Repositories" that links directly to the repo search page, there is a drop down titled "Repo"
that has "Repo Search" as (currently) the one and only option.  "Repo Search" goes where "Repositories" used to go,
to the repo search page.
This makes room to add additional functions to the repo
drop down menu, including commit download functions that are
planned for the future.
=> On course page, change repositories to repo drop down

dotenv.example
This PR updates dotenv.example with info on the scope needed for the machine user personal access token, and a link to documentation on getting the Slack OAuth values.
=> pc - update dotenv.example (GitHub OAuth scope, Slack OAuth)

app/assets/javascripts/courses.js, app/jobs/course/update_github_repos_job.rb, app/models/course.rb
In this commit, we add code that allows CSV files to have a GitHub id column.
If filled in, and if the GitHub id is valid, it will add the github id to the Roster Student
record.  This allows CSV download/upload to use used to migrate a course from one
instance of the app to another.
If the user has never logged in, the user record is created in the user table.
=> pc - allow CSV upload of GitHub ids

app/models/completed_job.rb
Because distance_of_time_in_words_to_now doesn't respect daylight savings time,
use distance_of_time_in_words with Time.zone.now instead
Fixes issue #270
=> pc - fix job elapsed time for in progress jobs

app/models/course.rb
This is a simple one line change to fix a bug.
* STR: Try to create a new course, and select webhooks enabled on create.
* Observed: Crashes
* Desired: Successfully creates course with web hooks enabled.
The key is to run the update_org_webhook method as an after_save rather than a before_save.
That way, you already have a course id.  You must have a course id in order to know what
the url will be for the webhooks.
=> pc - fix bug where enabling webhooks on a new course fails

.github/workflows/ci.yml, .gitignore, DOCS/cypress/README.md, Gemfile, Gemfile.lock, app/controllers/api/testhooks_controller.rb, config/environments/test.rb, config/initializers/cypress_on_rails.rb, config/routes.rb, package.json, test/cypress.json, test/cypress/app_commands/activerecord_fixtures.rb, test/cypress/app_commands/clean.rb, test/cypress/app_commands/eval.rb, test/cypress/app_commands/factory_bot.rb, test/cypress/app_commands/log_fail.rb, test/cypress/app_commands/scenarios/basic.rb, test/cypress/cypress_helper.rb, test/cypress/fixtures/example.json, test/cypress/integration/courses_spec.js, test/cypress/integration/home_spec.js, test/cypress/plugins/index.js, test/cypress/support/commands.js, test/cypress/support/index.js, test/cypress/support/on-rails.js, test/factories/factories.rb, yarn.lock
In this PR, we add Cypress testing, using the cypress-on-rails gem.
Cypress testing will allow us to test the integration of React components into the app; these cannot be tested
with traditional controller tests, since the React components aren't available when doing traditional rails-based
controller tests.
The Github actions workflow is set up so that on failure, screenshots are saved as GitHub actions artifacts.  Videos are always saved, regardless of outcome.
A set of endpoints `/api/testhooks/*` is set up to assist with mocking authentication:
* These endpoints reject all requests *unless* the app is running in `RAILS_ENV-test` mode.
* When running in in `RAILS_ENV-test` mode, these endpoints accept requests without requiring authentication
* `/api/testhooks/login_student` logs in …
=> Add Cypress testing

package.json, yarn.lock
Based on this security warning:
```
Bump bootstrap from 3.3.7 to 3.4.1  dependencies javascript
#252 by dependabot bot was closed on May 21
1
5 bootstrap vulnerabilities found in yarn.lock on May 21
Remediation
Upgrade bootstrap to version 3.4.1 or later. For example:
bootstrap@^3.4.1:
version "3.4.1"
Always verify the validity and compatibility of suggestions with your codebase.
Details
CVE-2019-8331
moderate severity
Vulnerable versions: >= 3.0.0, < 3.4.1
Patched version: 3.4.1
In Bootstrap 4 before 4.3.1 and Bootstrap 3 before 3.4.1, XSS is possible in the tooltip or popover data-template attribute. For more information, see: https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/
CVE-2018-20677
low severity
Vulnerable versions: < 3.4.0
Patched version: 3.4.0
In Bootstrap …
```
=> pc - upgrade bootstrap because of GitHub security warning

DOCS/cypress/examples/actions.spec.js, DOCS/cypress/examples/aliasing.spec.js, DOCS/cypress/examples/assertions.spec.js, DOCS/cypress/examples/connectors.spec.js, DOCS/cypress/examples/cookies.spec.js, DOCS/cypress/examples/cypress_api.spec.js, DOCS/cypress/examples/files.spec.js, DOCS/cypress/examples/local_storage.spec.js, DOCS/cypress/examples/location.spec.js, DOCS/cypress/examples/misc.spec.js, DOCS/cypress/examples/navigation.spec.js, DOCS/cypress/examples/network_requests.spec.js, DOCS/cypress/examples/querying.spec.js, DOCS/cypress/examples/spies_stubs_clocks.spec.js, DOCS/cypress/examples/traversal.spec.js, DOCS/cypress/examples/utilities.spec.js, DOCS/cypress/examples/viewport.spec.js, DOCS/cypress/examples/waiting.spec.js, DOCS/cypress/examples/window.spec.js, DOCS/cypress/rails_examples/advance_factory_bot_spec.js, DOCS/cypress/rails_examples/other_spec.js, DOCS/cypress/rails_examples/using_factory_bot_spec.js, DOCS/cypress/rails_examples/using_fixtures_spec.js, DOCS/cypress/rails_examples/using_scenarios_spec.js
This PR only puts the cypress examples and the cypress-on-rails examples into the DOCS/cypress folder.
This is separated out to make the actual cypress PR less cluttered.
=> pc - add cypress examples into DOCS

app/controllers/courses_controller.rb
Hotfix to bug where student cannot login because HSU roster emails were in uppercase
but student typically put in lowercase in GitHub for example.
This PR makes the comparison case insensitive.
=> pc - make email comparison case insensitive

test/controllers/courses_controller_test.rb, test/fixtures/roster_students.yml
A bug was reported by an instructor using the app, where a student's emai
email address on the course roster was in uppercase, but in practice
they always used lowercase.  In truth, email addresses are typically
case insensitive.   This test covers that.
It is written in the style of the tests currently in the test suite,
which is NOT the best style; it relies on fixtures far from the tests
themselves.  Refactoring that is a larger project; for now, we just needed
to get a test in to cover this case.
=> pc - add test for mismatch in email case

Gemfile, Gemfile.lock, app/controllers/admin_controller.rb, app/models/course.rb, app/models/user.rb, app/views/admin/dashboard.html.erb, config/initializers/admin_access.rb, config/initializers/flipper.rb, config/routes.rb, db/migrate/20200824183703_create_flipper_tables.rb, db/schema.rb
In this PR, we enable feature toggling using the [flipper gem](https://github.com/jnunemaker/flipper).
This implements the Feature Toggle application development pattern as described on this wikipedia page:
* <https://en.wikipedia.org/wiki/Feature_toggle>
With this PR, admin users can now access an endpoint `/flipper` which provides a UI where individual named features
can be turned on or off for:
* All users
* Specific users (by GitHub id)
* Specific courses (by Course name)
This allows us to put new features into the code base that:
* Might confuse existing users, courses
* Might not be ready for production, but that we want to  start integrating into the code base
The goal is more frequent PRs being merged into master, with less risk.
To execute some code only if a feature is on, use: …
=> Feature toggle with flipper

.github/workflows/ci.yml
In this PR, propose a quick and dirty (though specifically "not recommended") fix to the broken CI/CD pipeline.
The CI/CD pipeline via GitHub actions is currently broken because of a change made by GitHub to work around a security vulnerability, described here: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
The quick and dirty fix is to add this line into the workflow as done in #321 
```yml
env:
ACTIONS_ALLOW_UNSECURE_COMMANDS: true
```
But this is not recommended.  A better approach is to use something called [environment files](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files).   This PR uses this approach.
We should merge either this PR or #321 first before anything else, to restore …
=> pc - try using environment file instead of setting env values directly

app/controllers/courses_controller.rb, app/models/course.rb, app/views/courses/_form.html.erb, db/migrate/20210329190634_add_term_to_courses.rb, db/schema.rb, test/controllers/courses_controller_test.rb
User Story: 
As an instructor setting up a new course, I can enter a "term" for the course so that users can find course instances more easily.
Acceptance Criteria:
The "term" field is currently an optional string. This accommodates old courses without terms, and the wide variety in term naming systems used by different schools.
=> Add a "term" field to Courses

app/javascript/components/Courses/CoursesIndex.jsx
In this PR, we fix the failing cypress test on the branch vi-courses-react.
The cypress test is looking for the id `courses-table` to be on the table on the courses page.   This restores it.
Note: to run cypress tests locally:
1. Open two terminal windows, and cd into the root of the repo.
2. In the first, run the script `./cypress_server`
3. In the second, run the script `./cypress_run`
4. See the same results that you would get on CI.
=> pc - fix failing cypress test

app/jobs/repo/course_github_repo_get_issues.rb, app/models/github_repo.rb, db/migrate/20210629065128_add_number_to_repo_issue_event.rb, db/schema.rb
User Story: When downloading a CSV of issues from a repository or an organization, the resulting CSV includes an issue number column so that it can be filtered or sorted by issue number.
Addresses Issue #379.
Acceptance Criteria:
=> CSV Issue Downloads Now Include Issue Number

app/jobs/repo/course_github_repo_get_commits.rb
In this draft PR, we modify the job to get commits for a project repo so that it only pulls commits that are within the start and end date of the course.
Brian's testing
With proper start date and end date:
With start date changed to a few days forward (same end date as before):
No start date and end dates (before fix):
No start date and end dates (after fix):
=> pc/bh - a start at adjusting get commit job to respect course dates

app/controllers/api/job_log_controller.rb
The api for job logs has multiple endpoints: one at the entire app level has no values for the parameters for course and repo.
Rather than passing these parameters (whose value will always be nil), it is likely better to write a line of code that shows them as nil.
Before
```
joblog = CompletedJob.last_ten_jobs(params[:course_id],params[:github_repo_id])
```
After:
```
joblog = CompletedJob.last_ten_jobs(nil,nil)
```
This will not change functionality; just readability of the code.  The developer no longer has to "figure out" that these parameters will always be nil.
=> Fixed a line in job log code for readability

app/javascript/components/Course/Analytics/ChangeAnalytics.jsx, app/javascript/components/Course/Analytics/CommitsAnalytics.jsx, app/javascript/components/Course/OrgTeams/CourseOrgTeam.jsx, app/javascript/components/Course/OrgTeams/CourseOrgTeamsIndex.jsx
In this PR, I refactored the github teams page to be a dropdown instead of a table. The user can select a team from a list of teams and the page will rerender to show information about that team directly on that page without leading to a show page.
Before:
After:
=> Refactored teams page to be a dropdown instead of a table

app/controllers/courses/github_repos_controller.rb, db/schema.rb, yarn.lock
Apparently, this was a one line change - I missed to include the project repo level job to the job list
Before:  On a individual project repo, the "Get Pull Requests for this repo"  job is missing:
After:  The get PR data is there!
=> at - add repo level job to the job list for pull requests' data 

app/views/courses/_show_admin.html.erb
In this PR, I changed the link for "teams" on the student list to lead to the teams show page that includes more useful information, rather than leading the user to the teams github page.
Before:
This link led to the GitHub page for the team
e.g. this (not the right team, but that's the general idea)
After: it leads to the show page for the team:
=> Changed link for teams on student list to lead to team show page

app/models/github_repo.rb
In this PR, we make a HOTFIX to address a bug with CSV commit downloads.
We are getting errors when certain new fields are nil.   This PR adds guard code to handle this case.
=> HOTFIX: handle case where excluded fields are nil

app/controllers/api/courses/org_teams_controller.rb, app/javascript/components/Course/Analytics/ChangeAnalytics.jsx, app/javascript/components/Course/Analytics/CommitsAnalytics.jsx, app/javascript/components/Course/OrgTeams/CourseOrgTeam.jsx, db/migrate/20210803074907_add_repo_id_to_org_team.rb, db/schema.rb
In this PR, I added a dropdown on each team page that allows the user to associate a team with a project repo. On change, the page will refresh all analytics to match the new project repo associated with the team.
=> Added ability to associate a project repo to a team

app/jobs/course/create_assignment_repos_job.rb
The job to create assignment repos was flaky--many repos were not created.
Root cause was determined to be these errors:
```
2021-11-03T20:18:00.848898+00:00 app[web.1]: CREATION ERROR for lab05-rmarangoly for user rmarangoly {:data=>{:createRepository=>nil}, :errors=>[{:type=>"RATE_LIMITED", :path=>["createRepository"], :locations=>[{:line=>2, :column=>11}], :message=>"You have created too many repositories, too quickly. Please try again later."}]}
```
Attempt to fix by adding a  delay (plus a Rails.logger.info so we can better track down assignment creation attempts and find the associated logging if/when debugging future problems.)
delay is configurable via environment variable `SLEEP_DELAY`
value is sleep time in seconds (converted to integer, and passed directly to ruby `sleep` )
=> pc - add 2 second delay to creating assignment repos

Gemfile, Gemfile.lock
This PR removes the unused `mini_racer` dependency, preventing issues with installing `libv8`.
=> Remove mini_racer dependency

Gemfile.lock, app/controllers/api/courses_controller.rb, app/javascript/components/Courses/CoursesIndex.jsx, app/models/course.rb, app/views/api/courses/_course.json.jbuilder, db/schema.rb, test/controllers/api/courses_controller_test.rb, test/factories/factories.rb
Added check on the get courses api to return only student and instructor courses instead of all courses if a non-admin user is logged in. Also the edit and delete button is only shown on instructor courses or all courses if you're an admin.
=> Fix get course controller to return correct courses list

app/controllers/courses_controller.rb, app/models/course.rb, app/views/courses/_show_admin.html.erb, test/controllers/courses_controller_test.rb, test/helpers/octokit_stub_helper.rb
Closes #510 
In this PR, we add the ability for instructors to see current default member permissions for a course organization.
We also provide a warning if it is not the recommended value and a link to the place to change it.
The link takes you directly to the github settings page where the permissions can be changed.
=> Sk show default member permissions

db/schema.rb
In this PR, we simply update schema.rb to be up to date with recent database changes.
This file probably should have been included in a previous PR but was somehow missed.
=> pc - update schema.rb to match recent db changes

app/controllers/courses_controller.rb, app/javascript/components/Course/JoinPage.jsx, app/javascript/packs/react-bundle.js, app/javascript/stories/Course/JoinPage.stories.mdx, app/models/course.rb, app/models/user.rb, app/views/courses/_show_student.html.erb, app/views/courses/join.html.erb, app/views/courses/show.html.erb, app/views/layouts/courses.html.erb, test/controllers/courses_controller_test.rb, test/javascript/components/Course/JoinPage.test.js
In this PR added a new join page instead of a alert to accept the invitation when joining a course for a student.
Closes #503 
Before, when you join a course, you get this very subtle alert at the top of the screen, which is easy to miss, and many students don't read it.
After: when you join a course, you get this page, which, we hope will be a lot more noticable, and student will know what they need to do next.
=> as-added a new join page instead of a alert to accept the invitation when joining a course for a student

app/controllers/courses_controller.rb, test/controllers/courses_controller_test.rb
Closes #504 
Fixed issue when user tries to join a course and is not successful, redirect them to the home page, not the courses page.
=> kz-set redirect to home page rather than courses page on error when joining a course

app/controllers/courses/roster_students_controller.rb
In this PR, we fix a bug where the downloaded JSON file had a filename ending in CSV. Now, it has a filename ending in .json
Closes #507
=> al - fixes json filename bug
